# Generated by Django 5.0.4 on 2024-04-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_uploadedfile_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
